/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shoes.ui;

import com.formdev.flatlaf.FlatLightLaf;
import com.shoes.utils.Auth;
import com.shoes.utils.JDBCHelper;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author THEQUANG
 */
public class Main extends javax.swing.JFrame {

    Color DefaultColor, ClickedColor;

    /**
     * Creates new form Main
     */
    public Main() throws UnsupportedLookAndFeelException {
        initComponents();
        setLocationRelativeTo(this);
        UIManager.setLookAndFeel(new FlatLightLaf());
        UIManager.put("Table.showVerticalLines", true);
        UIManager.put("Table.showHorizontalLines", true);
        new ManHinhChao(this, true).setVisible(true);
        new LoginForm(this, true).setVisible(true);
        loadTenNV();
        JDBCHelper.getConnection();
        DefaultColor = new Color(0,204,204);
        ClickedColor = new Color(0,153,153);
        Nav.setBackground(DefaultColor);
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        Content.removeAll();
        TrangChuForm ttf = new TrangChuForm();
        Content.add(ttf).setVisible(true);
        
    }
    void loadTenNV(){
        jLabel1.setText("Hi, " +Auth.isTen());
    }
    void dangXuat(){
        Auth.clear();
        new LoginForm(this, true).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TrangChu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SanPham = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BanHang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        HoaDon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NhanVien = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        KhachHang = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        KhuyenMai = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DoiMatKhau = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nav.setBackground(new java.awt.Color(0, 204, 204));
        Nav.setForeground(new java.awt.Color(255, 255, 255));
        Nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hi, Admin");
        Nav.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 55, 220, -1));

        TrangChu.setBackground(new java.awt.Color(0, 204, 204));
        TrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TrangChu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TrangChuMouseMoved(evt);
            }
        });
        TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrangChuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrangChuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TrangChuMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Home.png"))); // NOI18N
        jLabel3.setText("TRANG CHỦ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrangChuLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );

        Nav.add(TrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        SanPham.setBackground(new java.awt.Color(0, 204, 204));
        SanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanPham.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SanPhamMouseMoved(evt);
            }
        });
        SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanPhamMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SanPhamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SanPhamMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Brief case.png"))); // NOI18N
        jLabel4.setText("SẢN PHẨM");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout SanPhamLayout = new javax.swing.GroupLayout(SanPham);
        SanPham.setLayout(SanPhamLayout);
        SanPhamLayout.setHorizontalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        SanPhamLayout.setVerticalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Nav.add(SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, -1));

        BanHang.setBackground(new java.awt.Color(0, 204, 204));
        BanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BanHang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BanHangMouseMoved(evt);
            }
        });
        BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanHangMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BanHangMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Add to basket.png"))); // NOI18N
        jLabel5.setText("BÁN HÀNG");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BanHangLayout = new javax.swing.GroupLayout(BanHang);
        BanHang.setLayout(BanHangLayout);
        BanHangLayout.setHorizontalGroup(
            BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BanHangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        BanHangLayout.setVerticalGroup(
            BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BanHangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Nav.add(BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, -1));

        ThongKe.setBackground(new java.awt.Color(0, 204, 204));
        ThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongKe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ThongKeMouseMoved(evt);
            }
        });
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ThongKeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongKeMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Bar chart.png"))); // NOI18N
        jLabel6.setText("THỐNG KÊ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Nav.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, -1));

        HoaDon.setBackground(new java.awt.Color(0, 204, 204));
        HoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HoaDon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HoaDonMouseMoved(evt);
            }
        });
        HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoaDonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDonMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Price list.png"))); // NOI18N
        jLabel7.setText("HOÁ ĐƠN");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout HoaDonLayout = new javax.swing.GroupLayout(HoaDon);
        HoaDon.setLayout(HoaDonLayout);
        HoaDonLayout.setHorizontalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        HoaDonLayout.setVerticalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Nav.add(HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, -1));

        NhanVien.setBackground(new java.awt.Color(0, 204, 204));
        NhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhanVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                NhanVienMouseMoved(evt);
            }
        });
        NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhanVienMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Clien list.png"))); // NOI18N
        jLabel8.setText("NHÂN VIÊN");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout NhanVienLayout = new javax.swing.GroupLayout(NhanVien);
        NhanVien.setLayout(NhanVienLayout);
        NhanVienLayout.setHorizontalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        NhanVienLayout.setVerticalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Nav.add(NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 220, -1));

        KhachHang.setBackground(new java.awt.Color(0, 204, 204));
        KhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhachHang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                KhachHangMouseMoved(evt);
            }
        });
        KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhachHangMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KhachHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KhachHangMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Users.png"))); // NOI18N
        jLabel9.setText("KHÁCH HÀNG");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout KhachHangLayout = new javax.swing.GroupLayout(KhachHang);
        KhachHang.setLayout(KhachHangLayout);
        KhachHangLayout.setHorizontalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachHangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        KhachHangLayout.setVerticalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachHangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Nav.add(KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 50));

        KhuyenMai.setBackground(new java.awt.Color(0, 204, 204));
        KhuyenMai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhuyenMai.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                KhuyenMaiMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                KhuyenMaiMouseMoved(evt);
            }
        });
        KhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhuyenMaiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KhuyenMaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KhuyenMaiMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Label.png"))); // NOI18N
        jLabel11.setText("KHUYẾN MÃI");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout KhuyenMaiLayout = new javax.swing.GroupLayout(KhuyenMai);
        KhuyenMai.setLayout(KhuyenMaiLayout);
        KhuyenMaiLayout.setHorizontalGroup(
            KhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhuyenMaiLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel11)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        KhuyenMaiLayout.setVerticalGroup(
            KhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhuyenMaiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Nav.add(KhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 220, -1));

        DoiMatKhau.setBackground(new java.awt.Color(0, 204, 204));
        DoiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoiMatKhau.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DoiMatKhauMouseMoved(evt);
            }
        });
        DoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoiMatKhauMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoiMatKhauMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DoiMatKhauMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Refresh.png"))); // NOI18N
        jLabel12.setText("ĐỔI MẬT KHẨU");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel12MouseMoved(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout DoiMatKhauLayout = new javax.swing.GroupLayout(DoiMatKhau);
        DoiMatKhau.setLayout(DoiMatKhauLayout);
        DoiMatKhauLayout.setHorizontalGroup(
            DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiMatKhauLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel12)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        DoiMatKhauLayout.setVerticalGroup(
            DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiMatKhauLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Nav.add(DoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 220, -1));

        DangXuat.setBackground(new java.awt.Color(0, 204, 204));
        DangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DangXuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DangXuatMouseMoved(evt);
            }
        });
        DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DangXuatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangXuatMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shoes/img/Exit.png"))); // NOI18N
        jLabel10.setText("ĐĂNG XUẤT");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel10)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangXuatLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(16, 16, 16))
        );

        Nav.add(DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 220, -1));

        getContentPane().add(Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 710));

        Content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1200, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        // TODO add your handling code here:
        TrangChu.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(ClickedColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        TrangChuForm ttf = new TrangChuForm();
        Content.removeAll();
        Content.add(ttf).setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel3MouseExited

    private void TrangChuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMouseMoved
        // TODO add your handling code here:
        TrangChu.setBackground(ClickedColor);
    }//GEN-LAST:event_TrangChuMouseMoved

    private void TrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMouseClicked
        // TODO add your handling code here:
        TrangChuForm ttf = new TrangChuForm();
        Content.removeAll();
        Content.add(ttf).setVisible(true);
    }//GEN-LAST:event_TrangChuMouseClicked

    private void TrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMouseExited
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
    }//GEN-LAST:event_TrangChuMouseExited

    private void TrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(ClickedColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TrangChuMousePressed

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        // TODO add your handling code here:
        SanPham.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        if (Auth.isManager()) {
            SanPhamForm spf = new SanPhamForm();
            Content.removeAll();
            Content.add(spf).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Bạn không có đủ quyền hạn !");
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        SanPham.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel4MouseExited

    private void SanPhamMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMouseMoved
        // TODO add your handling code here:
        SanPham.setBackground(ClickedColor);
    }//GEN-LAST:event_SanPhamMouseMoved

    private void SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMouseClicked
        // TODO add your handling code here:
        SanPhamForm spf = new SanPhamForm();
        Content.removeAll();
        Content.add(spf).setVisible(true);
    }//GEN-LAST:event_SanPhamMouseClicked

    private void SanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMouseExited
        // TODO add your handling code here:
        SanPham.setBackground(DefaultColor);
    }//GEN-LAST:event_SanPhamMouseExited

    private void SanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(ClickedColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_SanPhamMousePressed

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
        // TODO add your handling code here:
        BanHang.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel5MouseMoved

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(ClickedColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        BanHangForm bhf = new BanHangForm();
        Content.removeAll();
        Content.add(bhf).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        BanHang.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel5MouseExited

    private void BanHangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanHangMouseMoved
        // TODO add your handling code here:
        BanHang.setBackground(ClickedColor);
    }//GEN-LAST:event_BanHangMouseMoved

    private void BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanHangMouseClicked
        // TODO add your handling code here:
        BanHangForm bhf = new BanHangForm();
        Content.removeAll();
        Content.add(bhf).setVisible(true);
    }//GEN-LAST:event_BanHangMouseClicked

    private void BanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanHangMouseExited
        // TODO add your handling code here:
        BanHang.setBackground(DefaultColor);
    }//GEN-LAST:event_BanHangMouseExited

    private void BanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanHangMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(ClickedColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_BanHangMousePressed

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
        // TODO add your handling code here:
        ThongKe.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);   
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(ClickedColor);
        ThongKeForm tkf = new ThongKeForm();
        Content.removeAll();
        Content.add(tkf).setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel6MouseExited

    private void ThongKeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseMoved
        // TODO add your handling code here:
        ThongKe.setBackground(ClickedColor);
    }//GEN-LAST:event_ThongKeMouseMoved

    private void ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseClicked
        // TODO add your handling code here:
        ThongKeForm tkf = new ThongKeForm();
        Content.removeAll();
        Content.add(tkf).setVisible(true);
    }//GEN-LAST:event_ThongKeMouseClicked

    private void ThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseExited
        // TODO add your handling code here:
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_ThongKeMouseExited

    private void ThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(ClickedColor);
    }//GEN-LAST:event_ThongKeMousePressed

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        // TODO add your handling code here:
        HoaDon.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(ClickedColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        HoaDonForm hdf = new HoaDonForm();
        Content.removeAll();
        Content.add(hdf).setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel7MouseExited

    private void HoaDonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseMoved
        // TODO add your handling code here:
        HoaDon.setBackground(ClickedColor);
    }//GEN-LAST:event_HoaDonMouseMoved

    private void HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseClicked
        // TODO add your handling code here:
        HoaDonForm hdf = new HoaDonForm();
        Content.removeAll();
        Content.add(hdf).setVisible(true);
    }//GEN-LAST:event_HoaDonMouseClicked

    private void HoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseExited
        // TODO add your handling code here:
        HoaDon.setBackground(DefaultColor);
    }//GEN-LAST:event_HoaDonMouseExited

    private void HoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(ClickedColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_HoaDonMousePressed

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
        // TODO add your handling code here:
        NhanVien.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel8MouseMoved

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(ClickedColor);
        ThongKe.setBackground(DefaultColor);
        NhanVienForm nvf = new NhanVienForm();
        Content.removeAll();
        Content.add(nvf).setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        NhanVien.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel8MouseExited

    private void NhanVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMouseMoved
        // TODO add your handling code here:
        NhanVien.setBackground(ClickedColor);
    }//GEN-LAST:event_NhanVienMouseMoved

    private void NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMouseClicked
        // TODO add your handling code here:
        NhanVienForm nvf = new NhanVienForm();
        Content.removeAll();
        Content.add(nvf).setVisible(true);
    }//GEN-LAST:event_NhanVienMouseClicked

    private void NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMouseExited
        // TODO add your handling code here:
        NhanVien.setBackground(DefaultColor);
    }//GEN-LAST:event_NhanVienMouseExited

    private void NhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(ClickedColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_NhanVienMousePressed

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        // TODO add your handling code here:
        KhachHang.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(ClickedColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        KhachHangForm khf = new KhachHangForm();
        Content.removeAll();
        Content.add(khf).setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        KhachHang.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel9MouseExited

    private void KhachHangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMouseMoved
        // TODO add your handling code here:
        KhachHang.setBackground(ClickedColor);
    }//GEN-LAST:event_KhachHangMouseMoved

    private void KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMouseClicked
        // TODO add your handling code here:
        KhachHangForm khf = new KhachHangForm();
        Content.removeAll();
        Content.add(khf).setVisible(true);
    }//GEN-LAST:event_KhachHangMouseClicked

    private void KhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMouseExited
        // TODO add your handling code here:

        KhachHang.setBackground(DefaultColor);
    }//GEN-LAST:event_KhachHangMouseExited

    private void KhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(ClickedColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_KhachHangMousePressed

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
        // TODO add your handling code here:
        KhuyenMai.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel11MouseMoved

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        VoucherForm kmf = new VoucherForm();
        Content.removeAll();
        Content.add(kmf).setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        KhuyenMai.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel11MouseExited

    private void KhuyenMaiMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhuyenMaiMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_KhuyenMaiMouseDragged

    private void KhuyenMaiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhuyenMaiMouseMoved
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(DefaultColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        KhuyenMai.setBackground(ClickedColor);
    }//GEN-LAST:event_KhuyenMaiMouseMoved

    private void KhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhuyenMaiMouseClicked
        // TODO add your handling code here:
        VoucherForm kmf = new VoucherForm();
        Content.removeAll();
        Content.add(kmf).setVisible(true);
    }//GEN-LAST:event_KhuyenMaiMouseClicked

    private void KhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhuyenMaiMouseExited
        // TODO add your handling code here:
        KhuyenMai.setBackground(DefaultColor);
    }//GEN-LAST:event_KhuyenMaiMouseExited

    private void KhuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhuyenMaiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KhuyenMaiMousePressed

    private void jLabel12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseMoved
        // TODO add your handling code here:
        DoiMatKhau.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel12MouseMoved

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        DoiMatKhauForm mkf = new DoiMatKhauForm();
        Content.removeAll();
        Content.add(mkf).setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
        DoiMatKhau.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel12MouseExited

    private void DoiMatKhauMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoiMatKhauMouseMoved
        // TODO add your handling code here:
        DoiMatKhau.setBackground(ClickedColor);
    }//GEN-LAST:event_DoiMatKhauMouseMoved

    private void DoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoiMatKhauMouseClicked
        // TODO add your handling code here:
        DoiMatKhauForm mkf = new DoiMatKhauForm();
        Content.removeAll();
        Content.add(mkf).setVisible(true);
    }//GEN-LAST:event_DoiMatKhauMouseClicked

    private void DoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoiMatKhauMouseExited
        // TODO add your handling code here:
        DoiMatKhau.setBackground(DefaultColor);
    }//GEN-LAST:event_DoiMatKhauMouseExited

    private void DoiMatKhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoiMatKhauMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoiMatKhauMousePressed

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        // TODO add your handling code here:
        DangXuat.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(ClickedColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        dangXuat();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel10MouseExited

    private void DangXuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMouseMoved
        // TODO add your handling code here:
        DangXuat.setBackground(ClickedColor);
    }//GEN-LAST:event_DangXuatMouseMoved

    private void DangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMouseExited
        // TODO add your handling code here:
        DangXuat.setBackground(DefaultColor);
    }//GEN-LAST:event_DangXuatMouseExited

    private void DangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(DefaultColor);
        SanPham.setBackground(DefaultColor);
        BanHang.setBackground(DefaultColor);
        DangXuat.setBackground(ClickedColor);
        HoaDon.setBackground(DefaultColor);
        KhachHang.setBackground(DefaultColor);
        NhanVien.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_DangXuatMousePressed

    private void DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DangXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BanHang;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel DoiMatKhau;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JPanel KhachHang;
    private javax.swing.JPanel KhuyenMai;
    private javax.swing.JPanel Nav;
    private javax.swing.JPanel NhanVien;
    private javax.swing.JPanel SanPham;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
